### PR TITLE
Don't wait for localmsg before starting FG MIDlet

### PR DESCRIPTION
**Pull request by marco-c**
This would fix https://github.com/mozilla/j2me.js/issues/1400.
I can't reproduce the issue that made us revert it.

### CODE REVIEW

**Comment by mykmelez** [comment]
I can't reproduce it either on my Flame running FxOS 2.1. But the startup benchmark shows a regression rather than an improvement on that device:

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:34.0) Gecko/34.0 Firefox/34.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|       Test      | Baseline Mean |    Mean    |    +/-   |     %    |     P    |     Min    |     Max    | 
|:----------------|--------------:|-----------:|---------:|---------:|---------:|-----------:|-----------:|
| startupTime     |      11,991ms |   13,289ms |  1,298ms |    10.83 |    WORSE |   11,987ms |   16,772ms | 
| vmStartupTime   |       2,248ms |    2,208ms |    -40ms |    -1.78 |     SAME |    2,047ms |    2,465ms | 
| bgStartupTime   |       1,869ms |      888ms |   -981ms |   -52.50 |   BETTER |      787ms |    1,096ms | 
| fgStartupTime   |       7,873ms |   10,192ms |  2,320ms |    29.46 |    WORSE |    8,869ms |   13,436ms | 
| *totalSize*     |    *22,615kb* | *22,314kb* | *-301kb* |  *-1.33* | *BETTER* | *21,276kb* | *23,064kb* | 
| *domSize*       |        *71kb* |     *71kb* |    *0kb* |  *-0.03* |   *SAME* |     *71kb* |     *71kb* | 
| *styleSize*     |       *300kb* |    *299kb* |   *-1kb* |  *-0.38* |   *SAME* |    *291kb* |    *305kb* | 
| *jsObjectsSize* |    *15,556kb* | *15,486kb* |  *-70kb* |  *-0.45* | *BETTER* | *15,464kb* | *15,503kb* | 
| *jsStringsSize* |       *945kb* |    *653kb* | *-292kb* | *-30.91* | *BETTER* |    *652kb* |    *653kb* | 
| *jsOtherSize*   |     *5,518kb* |  *5,586kb* |   *68kb* |   *1.24* |   *SAME* |  *4,631kb* |  *6,266kb* | 
| *otherSize*     |       *225kb* |    *219kb* |   *-5kb* |  *-2.43* |   *SAME* |    *166kb* |    *271kb* | 
| *USS*           |    *49,637kb* | *49,523kb* | *-113kb* |  *-0.23* |   *SAME* | *47,988kb* | *50,636kb* | 
| *peakRSS*       |         *0kb* |    *NaNkb* |  *NaNkb* |    *NaN* |   *SAME* |    *NaNkb* |    *NaNkb* |

**Comment by mykmelez** [comment]
I was unsure about my procedure for the previous run, so I did another startup benchmark run, including redoing the baseline, and I got similar results:

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:34.0) Gecko/34.0 Firefox/34.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|       Test      | Baseline Mean |    Mean    |     +/-    |     %    |     P    |     Min    |     Max    | 
|:----------------|--------------:|-----------:|-----------:|---------:|---------:|-----------:|-----------:|
| startupTime     |      15,073ms |   17,412ms |    2,339ms |    15.52 |    WORSE |   16,375ms |   19,270ms | 
| vmStartupTime   |       2,554ms |    2,708ms |      154ms |     6.04 |    WORSE |    2,550ms |    2,983ms | 
| bgStartupTime   |       2,232ms |    1,216ms |   -1,017ms |   -45.55 |   BETTER |      979ms |    1,687ms | 
| fgStartupTime   |      10,287ms |   13,488ms |    3,201ms |    31.12 |    WORSE |   12,635ms |   15,294ms | 
| *totalSize*     |    *22,985kb* | *22,591kb* |   *-394kb* |  *-1.72* |   *SAME* | *21,759kb* | *25,928kb* | 
| *domSize*       |        *71kb* |     *71kb* |      *0kb* |  *-0.02* |   *SAME* |     *71kb* |     *72kb* | 
| *styleSize*     |       *303kb* |    *303kb* |     *-1kb* |  *-0.22* |   *SAME* |    *291kb* |    *306kb* | 
| *jsObjectsSize* |    *15,559kb* | *15,498kb* |    *-61kb* |  *-0.39* | *BETTER* | *15,470kb* | *15,521kb* | 
| *jsStringsSize* |       *930kb* |    *654kb* |   *-277kb* | *-29.74* | *BETTER* |    *653kb* |    *663kb* | 
| *jsOtherSize*   |     *5,872kb* |  *5,825kb* |    *-48kb* |  *-0.81* |   *SAME* |  *5,002kb* |  *9,155kb* | 
| *otherSize*     |       *249kb* |    *241kb* |     *-9kb* |  *-3.47* |   *SAME* |    *166kb* |    *286kb* | 
| *USS*           |    *50,331kb* | *49,119kb* | *-1,212kb* |  *-2.41* |   *SAME* | *47,464kb* | *57,260kb* | 
| *peakRSS*       |         *0kb* |    *NaNkb* |    *NaNkb* |    *NaN* |   *SAME* |    *NaNkb* |    *NaNkb* | 

@marco-c Can you do a startup benchmark run on your device to confirm?

**Comment by marco-c** [comment]
Mmmh, weird, I don't see how not waiting for localmsg to be present could make perf worse.
I expected some of the *bgStartupTime* time to move to *fgStartupTime*, but I wouldn't have expected an overall regression (and I did see an improvement when we last merged this).

> @marco-c Can you do a startup benchmark run on your device to confirm?

Yes, I will.

**Comment by marco-c** [comment]
This is from a run on 2.0:

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:32.0) Gecko/32.0 Firefox/32.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|       Test      | Baseline Mean |    Mean    |    +/-   |    %    |     P    |     Min    |     Max    | 
|:----------------|--------------:|-----------:|---------:|--------:|---------:|-----------:|-----------:|
| startupTime     |      19,243ms |   17,177ms | -2,067ms |  -10.74 |   BETTER |   14,972ms |   19,530ms | 
| vmStartupTime   |       2,738ms |    2,757ms |     19ms |    0.68 |     SAME |    2,433ms |    3,277ms | 
| bgStartupTime   |       3,752ms |    1,216ms | -2,536ms |  -67.60 |   BETTER |      752ms |    1,736ms | 
| fgStartupTime   |      12,753ms |   13,204ms |    451ms |    3.54 |     SAME |   11,725ms |   15,482ms | 
| *totalSize*     |    *33,898kb* | *34,427kb* |  *529kb* |  *1.56* |   *SAME* | *26,417kb* | *37,757kb* | 
| *domSize*       |       *104kb* |    *104kb* |    *0kb* |  *0.37* |  *WORSE* |    *102kb* |    *106kb* | 
| *styleSize*     |       *342kb* |    *343kb* |    *0kb* |  *0.10* |   *SAME* |    *340kb* |    *345kb* | 
| *jsObjectsSize* |    *19,647kb* | *19,372kb* | *-275kb* | *-1.40* | *BETTER* | *18,858kb* | *20,248kb* | 
| *jsStringsSize* |     *1,528kb* |  *1,591kb* |   *63kb* |  *4.11* |  *WORSE* |  *1,523kb* |  *1,690kb* | 
| *jsOtherSize*   |    *11,786kb* | *12,525kb* |  *740kb* |  *6.28* |   *SAME* |  *5,087kb* | *15,317kb* | 
| *otherSize*     |       *491kb* |    *492kb* |    *1kb* |  *0.12* |   *SAME* |    *456kb* |    *525kb* |

**Comment by marco-c** [comment]
Results from another run:

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:32.0) Gecko/32.0 Firefox/32.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|       Test      | Baseline Mean |    Mean    |    +/-    |    %    |    P    |     Min    |     Max    | 
|:----------------|--------------:|-----------:|----------:|--------:|--------:|-----------:|-----------:|
| startupTime     |      18,385ms |   17,418ms |    -967ms |   -5.26 |  BETTER |   15,064ms |   19,565ms | 
| vmStartupTime   |       2,680ms |    2,731ms |      51ms |    1.91 |    SAME |    2,447ms |    3,045ms | 
| bgStartupTime   |       3,577ms |    1,185ms |  -2,391ms |  -66.86 |  BETTER |      796ms |    1,500ms | 
| fgStartupTime   |      12,129ms |   13,502ms |   1,373ms |   11.32 |   WORSE |   11,659ms |   15,415ms | 
| *totalSize*     |    *32,506kb* | *34,920kb* | *2,415kb* |  *7.43* | *WORSE* | *28,323kb* | *38,576kb* | 
| *domSize*       |       *104kb* |    *105kb* |     *1kb* |  *0.76* | *WORSE* |    *102kb* |    *106kb* | 
| *styleSize*     |       *342kb* |    *342kb* |     *0kb* | *-0.01* |  *SAME* |    *338kb* |    *345kb* | 
| *jsObjectsSize* |    *19,071kb* | *19,600kb* |   *529kb* |  *2.78* | *WORSE* | *18,516kb* | *20,277kb* | 
| *jsStringsSize* |     *1,529kb* |  *1,678kb* |   *149kb* |  *9.76* | *WORSE* |  *1,609kb* |  *1,751kb* | 
| *jsOtherSize*   |    *10,974kb* | *12,712kb* | *1,739kb* | *15.85* | *WORSE* |  *5,434kb* | *15,762kb* | 
| *otherSize*     |       *487kb* |    *484kb* |    *-3kb* | *-0.68* |  *SAME* |    *429kb* |    *513kb* |

**Comment by mykmelez** [comment]
I just tested again, and I'm still seeing worse overall startup time. I'm not sure how that's possible either, and I'm also suspicious of the results, as memory minimization appears to take longer and longer with each round on this device. So I'm going to try testing on my 2.0 device (and possibly also try flashing this device with a newer version of 2.1).

**Comment by brendandahl** [comment]
Perhaps there's a difference in which commit you built your baselines off of? What are the commit id's?

**Comment by mykmelez** [comment]
> Perhaps there's a difference in which commit you built your baselines off of? What are the commit id's?

Hmm, git merge-base says it's e81d123c774e61e35f135282793c50e4d01de26c, but I may have merged since then. I'll rerun tests and answer this definitively a bit later.

**Comment by mykmelez** [comment]
> Hmm, git merge-base says it's e81d123, but I may have merged since then. I'll rerun tests and answer this definitively a bit later.

That should be the correct baseline. But I don't think a different baseline is causing my testing issues. I filed #1508 to track them.

**Comment by marco-c** [comment]
While investigating another thing, I've noticed there's a ~700 ms delay between the creation of the WaitUserInteractionThread and its execution. This PR removes the thread, so that delay is completely removed.

```
CREATE WaitUserInteractionThread AT: 5236
RUN WaitUserInteractionThread AT: 5933
```

And there's another delay (due to waiting localmsg) of ~1300 ms that this PR removes.

```
DONE WaitUserInteraction AT 5961.9271850000005
DONE WaitUserInteraction with localmsg AT 7269
```

**Comment by mykmelez** [comment]
I disabled memory benchmarking due to #1508, but I still see weird results:

|      Test     | Baseline Mean |   Mean   |    +/-   |    %   |    P   |    Min   |    Max   | 
|:--------------|--------------:|---------:|---------:|-------:|-------:|---------:|---------:|
| startupTime   |      15,962ms | 21,705ms |  5,743ms |  35.98 |  WORSE | 13,445ms | 75,252ms | 
| vmStartupTime |       2,434ms |  3,805ms |  1,371ms |  56.34 |  WORSE |  2,322ms | 11,462ms | 
| bgStartupTime |       3,916ms |  2,088ms | -1,828ms | -46.68 | BETTER |  1,010ms |  8,676ms | 
| fgStartupTime |       9,612ms | 15,812ms |  6,200ms |  64.50 |  WORSE |  9,105ms | 70,134ms | 

I don't think they should hold this up, however, since I don't trust my test environment anymore, and @marco-c's results have been consistent. Let's merge this once the trivial conflict is resolved.

**Pull request merged**
