### PR TITLE
Gfx fixes (native)

### PR DESCRIPTION
**Pull request by TimAbraldes**
This is the same as #1198 but using a native implementation of the `Graphics` object.

### CODE REVIEW

**Comment by TimAbraldes** [comment]
This is the result of running the startup benchmark on my favorite MIDlet (20 runs baseline, 20 runs benchmark) on my laptop:

|      Test     | Baseline Mean |    Mean   |    +/-   |   %   |       P       |    Min    |    Max    | 
|:--------------|--------------:|----------:|---------:|------:|--------------:|----------:|----------:|
| startupTime   |       2,742ms |   2,967ms |    226ms |  8.23 | INSIGNIFICANT |   2,253ms |   3,981ms | 
| totalSize     |     126,343kb | 125,666kb |   -677kb | -0.54 |        BETTER | 124,899kb | 126,209kb | 
| domSize       |         168kb |     168kb |      0kb |  0.01 | INSIGNIFICANT |     167kb |     173kb | 
| styleSize     |         441kb |     455kb |     14kb |  3.12 |         WORSE |     451kb |     480kb | 
| jsObjectsSize |      63,079kb |  64,106kb |  1,026kb |  1.63 |         WORSE |  63,336kb |  64,418kb | 
| jsStringsSize |       2,928kb |   2,930kb |      2kb |  0.07 | INSIGNIFICANT |   2,924kb |   2,958kb | 
| jsOtherSize   |      59,305kb |  57,558kb | -1,748kb | -2.95 |        BETTER |  57,209kb |  57,859kb | 
| otherSize     |         422kb |     450kb |     28kb |  6.73 | INSIGNIFICANT |     419kb |     689kb |

**Comment by mykmelez** [comment]
@TimAbraldes Between #1198 and this branch, which one do you think we should take? Neither impact startup perf/memory usage much. But this one is a smaller set of changes, even if it retains our custom implementation of *Graphics*; so it seems less risky.

Have you tried measuring runtime performance? We don't have a great metric for that, unfortunately, especially not for graphics operations. Perhaps you could use one of the graphics-intensive midlets in tests/midlets/ as the basis for a graphics benchmark we can add to bench/?

**Comment by mykmelez** [comment]
> @TimAbraldes Between #1198 and this branch, which one do you think we should take?

#1198 is closed; we have a winner! Looks like it needs conflict resolution, and I'm also interested in getting updated startup benchmark data. Presumably #1317's benchmark can be used to evaluate this as well?

**Comment by TimAbraldes** [comment]
> @TimAbraldes Between #1198 and this branch, which one do you think we should take? Neither impact startup perf/memory usage much. But this one is a smaller set of changes, even if it retains our custom implementation of Graphics; so it seems less risky.

Yeah; let's take the smaller set of changes. We can always switch to the reference implementation later, which is comparatively easier than switching back to a native implementation. I'm closing this PR now so I can re-submit the changes it makes as smaller individual PRs. Those will be easier to maintain and review.

> Have you tried measuring runtime performance? We don't have a great metric for that, unfortunately, especially not for graphics operations. Perhaps you could use one of the graphics-intensive midlets in tests/midlets/ as the basis for a graphics benchmark we can add to bench/?

I've created runtime performance tests in #1315 for this. I'll use them in the individual PRs that follow.

**Comment by TimAbraldes** [comment]
> #1198 is closed; we have a winner! Looks like it needs conflict resolution, and I'm also interested in getting updated startup benchmark data. Presumably #1317's benchmark can be used to evaluate this as well?

I didn't see a benchmark in #1317. Did I miss it? Or maybe you meant a different PR?

**Comment by mykmelez** [comment]
> I didn't see a benchmark in #1317. Did I miss it? Or maybe you meant a different PR?

Oops, sorry, I meant your benchmark in #1315!

**Pull request closed without merging**
