### PR TITLE
Enable closure optimizations for j2me.js and classes.jar.js

### PR DESCRIPTION
**Pull request by marco-c**
Requires https://github.com/mykmelez/closure-compiler/pull/1

### CODE REVIEW

**Comment by mykmelez** [comment]
I released a new build of the Closure compiler with the necessary change:

https://github.com/mykmelez/closure-compiler/releases/tag/v20150327

Can you update this pull request to make the tools/closure.jar target get that build instead of the old one? The new direct link to the closure.jar package is:

https://github.com/mykmelez/closure-compiler/releases/download/v20150327/closure.jar

**Comment by mykmelez** [comment]
Erm, I've moved the release to more clearly distinguish its tag from upstream tags.

Page:

https://github.com/mykmelez/closure-compiler/releases/tag/j2me.js-v20150327

Package:

https://github.com/mykmelez/closure-compiler/releases/download/j2me.js-v20150327/closure.jar

**Comment by marco-c** [comment]
These are the results from a run of the startup benchmark:
|      Test     | Baseline Mean |   Mean   |    +/-   |    %   |    P   |    Min   |    Max   | 
|:--------------|--------------:|---------:|---------:|-------:|-------:|---------:|---------:|
| startupTime   |      15,443ms | 14,714ms |   -729ms |  -4.72 | BETTER | 13,091ms | 17,731ms | 
| totalSize        |      31,387kb | 29,804kb | -1,583kb |  -5.04 | BETTER | 23,606kb | 31,867kb | 
| domSize        |          93kb |     95kb |      2kb |   2.31 |  WORSE |     94kb |     95kb | 
| styleSize        |         328kb |    335kb |      7kb |   2.11 |  WORSE |    333kb |    336kb | 
| jsObjectsSize |      16,317kb | 16,400kb |     83kb |   0.51 |  WORSE | 16,069kb | 16,755kb | 
| jsStringsSize |       1,632kb |  1,187kb |   -445kb | -27.25 | BETTER |  1,162kb |  1,193kb | 
| jsOtherSize   |      12,620kb | 11,377kb | -1,243kb |  -9.85 | BETTER |  5,101kb | 13,390kb | 
| otherSize     |         397kb |    410kb |     13kb |   3.30 |  WORSE |    378kb |    420kb |

**Comment by mykmelez** [comment]
Looks good, just needs conflict resolution.

**Pull request merged**
