### PR TITLE
ASM.jsify VM, WIP

### PR DESCRIPTION
**Pull request by mbebenita**
This is an attempt to lower the abstraction level on top of which the VM is built.

1. The first part of this PR changes the way we represent the call stack. Instead of representing the Java stack as array of frames (arrays) into which we push/pop values of different types, we now use one large typed array and do our own stack frame handling within it.
2. The VM aliases a typed array heap from a `asm.js` module and uses `malloc`/`free` to allocate stack space. This is convenient because it allows us to call into `C/C++` code whenever we need to do some heavy lifting.

### CODE REVIEW

**Comment by mbebenita** [comment]
Nearly all opcodes are implemented now.

**Comment by mbebenita** [comment]
So far, `148 class pass, 0 class fail, 2758ms`

**Comment by mbebenita** [comment]
As of now, the remaining failing tests are:

com.sun.midp.io.j2me.socket.StressTestSocket 
com.sun.midp.rms.TestRecordStoreFileNatives 
com.sun.midp.ssl.TestSSLStreamConnection
gnu.testlet.java.io.ByteArrayInputStream.ProtectedVars 
javax.microedition.io.TestHttpsConnection

**Comment by marco-c** [comment]
Only gnu.testlet.java.io.ByteArrayInputStream.ProtectedVars is failing for me (in the browser).

**Comment by marco-c** [comment]
This PR includes self-hosting String and other classes that were previously slower as self-hosted. Is perf better now?

**Comment by marco-c** [comment]
https://github.com/mbebenita/j2me.js/pull/27 fixes the build on Linux.
https://github.com/mbebenita/j2me.js/pull/28 fixes the ProtectedVars test (it is passing now, so it's just a matter of replacing *todo* with *check).

**Comment by mbebenita** [comment]
> Is self-hosting required or can we do that in another PR? (This way this PR would be smaller and we could investigate performance changes of self-hosting classes one by one)

It simplifies things quite a lot to not have to worry about any JS values dangling off of Java objects. I agree with you that it makes this PR larger, but it is a lot cleaner. I'd be in favor of reapplying some of the optimizations on top of the current design.

What optimization offered the biggest perf improvement?

**Comment by marco-c** [comment]
> What optimization offered the biggest perf improvement?

I don't recall what in particular, but I recall we had to back out self-hosting of these classes because it was slower.
Self-hosting String caused a startup regression in https://github.com/mozilla/j2me.js/pull/1314.

**Comment by mykmelez** [comment]
Right now we're about 2x slower on this branch in the startup benchmark on desktop with a complex midlet:

|         Test         | Baseline Mean |     Mean    |     +/-     |     %     |     P    |      Min     |      Max      | 
|:---------------------|--------------:|------------:|------------:|----------:|---------:|-------------:|--------------:|
| startupTime          |         867ms |     1,673ms |       807ms |     93.05 |    WORSE |      1,612ms |       1,916ms | 
| vmStartupTime        |         331ms |       544ms |       213ms |     64.22 |    WORSE |        520ms |         635ms | 
| bgStartupTime        |          80ms |       104ms |        24ms |     29.47 |    WORSE |         99ms |         116ms | 
| fgStartupTime        |         251ms |       485ms |       234ms |     93.18 |    WORSE |        461ms |         630ms | 
| fgRefreshStartupTime |          83ms |       163ms |        80ms |     95.99 |    WORSE |        154ms |         186ms | 
| *totalSize*          |    *29,077kb* | *437,607kb* | *408,530kb* | *1404.97* |  *WORSE* |  *436,624kb* |   *437,910kb* | 
| *domSize*            |       *167kb* |     *168kb* |       *0kb* |    *0.18* |  *WORSE* |      *168kb* |       *168kb* | 
| *styleSize*          |       *435kb* |     *435kb* |       *0kb* |    *0.02* |  *WORSE* |      *435kb* |       *435kb* | 
| *jsObjectsSize*      |    *18,791kb* | *428,780kb* | *409,989kb* | *2181.84* |  *WORSE* |  *428,771kb* |   *428,783kb* | 
| *jsStringsSize*      |     *1,012kb* |     *471kb* |    *-541kb* |  *-53.48* | *BETTER* |      *470kb* |       *471kb* | 
| *jsOtherSize*        |     *8,224kb* |   *7,304kb* |    *-920kb* |  *-11.19* | *BETTER* |    *6,333kb* |     *7,593kb* | 
| *otherSize*          |       *448kb* |     *450kb* |       *2kb* |    *0.40* |   *SAME* |      *447kb* |       *463kb* | 
| *USS*                |         *n/a* |     *NaNkb* |       *n/a* |     *n/a* |    *n/a* | *Infinitykb* | *-Infinitykb* | 
| *peakRSS*            |   *313,464kb* | *723,118kb* | *409,654kb* |  *130.69* |  *WORSE* |  *659,840kb* |   *744,100kb* | 

But there are a lot of moving pieces here; it's hard to say if String/StringBuffer self-hosting is related. We also aren't compiling anything at the moment (neither AOT nor JIT).

**Comment by mbebenita** [comment]
You'll probably notice that the memory usage has increased 20X, this is primarily because we currently allocate a very large heap. We also allocate an equally large JS Object array and null it out at startup, which takes a significant amount of time.

This is actually pretty good, I was expecting a lot worse at first, until all the pieces land.

**Comment by marco-c** [comment]
I guess we can close this in favor of https://github.com/mozilla/j2me.js/pull/1598.

**Pull request closed without merging**
