### PR TITLE
pre-allocate circular buffers to avoid expensive allocations during profiling

### PR DESCRIPTION
**Pull request by mykmelez**
*TimelineBuffer* initializes itself lazily, including creating two circular buffers (one wrapping an *Int32Array* and another wrapping a *Float64Array*). That can skew results when a method being measured by one timeline triggers the creation of another timeline, since occasionally the browser takes a while to create those typed arrays (particularly the *Float64Array* one).

In particular, when profiling a midlet that creates many threads on desktop, *Thread.start0* is one of the most expensive methods in the aggregate method statistics produced by #1569:

> java/lang/Thread.start0.()V: count: 11, self: 94.898 ms, total: 94.898 ms.

But most of the cost is because it creates a new *Context*, which creates a new *TimelineBuffer*, and then starts the context, which enters *org/mozilla/internal/Sys.runThread.(Ljava/lang/Thread;)V* in the new context's timeline, triggering initialization of the timeline (and potentially expensive allocations of the circular buffers). So the cost is actually excise, overhead from profiling, rather than an accurate reflection of the cost of the method.

This branch frontloads that cost during startup by pre-allocating a set of circular buffers for the timeline buffers to use, so it doesn't affect the cost of such methods. With this change, *Thread.start0* is cheap:

> java/lang/Thread.start0.()V: count: 11, self: 2.800 ms, total: 2.800 ms.

### CODE REVIEW

**Comment by brendandahl** [comment]
BTW, if you've had certain timelines overflow, I recommend doing:

-      this._marks = new Shumway.CircularBuffer(Int32Array, 20);
-      this._times = new Shumway.CircularBuffer(Float64Array, 20);
+      this._marks = new Shumway.CircularBuffer(Int32Array, 23);
+      this._times = new Shumway.CircularBuffer(Float32Array, 23);

**Comment by marco-c** [comment]
This explains https://github.com/mozilla/j2me.js/issues/1541

**Comment by mykmelez** [comment]
> BTW, if you've had certain timelines overflow, I recommend doing:

Hmm, I'm unsure if I've seen that. It doesn't look like *CircularBuffer* warns in that case, nor does *TimelineBuffer* check *CircularBuffer.isFull* before calling *CircularBuffer.write*. I suppose it would show up in missing profile data.

In any case, that issue seems orthogonal to the changes here, which just alter the time at which the buffers are allocated. They still start (and stop) being used at the same time, so they should still overflow (or not) as they did before.

**Comment by mykmelez** [comment]
> BTW, if you've had certain timelines overflow, I recommend doing:

Per our discussion in IRC, I parameterized the buffer size in 1d7905d and 8923e58 to make it easier to change it.

**Pull request merged**
