### PR TITLE
Don't override ResourceInputStream::read and ResourceInputStream::availa...

### PR DESCRIPTION
**Pull request by marco-c**
...ble

This will avoid the slow *getField* calls.

@mbebenita saw these being called > 80000 times on startup.

### CODE REVIEW

**Comment by mykmelez** [comment]
What's the perf win here?

**Comment by marco-c** [comment]
*getField* is slower than using the new binding system, because it needs to split the key string into name and signature (and 'I' or 'S' for instance or static) and then convert them to UTF8 and iterate over the fields until it finds the right one.

**Comment by mykmelez** [comment]
> getField is slower than using the new binding system, because it needs to split the key string into name and signature (and 'I' or 'S' for instance or static) and then convert them to UTF8 and iterate over the fields until it finds the right one.

Yes, I understand the theoretical win, but I'd like to know if this has a practical impact on an actual measurement.

**Comment by marco-c** [comment]
I've measured on desktop:
startupTime |       1,993ms | 1,902ms | -91ms | -4.58% | INSIGNIFICANT | 1,748ms | 2,270ms

**Comment by marco-c** [comment]
I'm writing a benchmark for ResourceInputStream.

**Comment by marco-c** [comment]
~200 ms for both *available* and *read single* before, ~40 ms for *available* and ~15 ms for *read single* after

**Comment by mykmelez** [comment]
Thanks. It's what we expected, but it's good to have the data to back up our assumptions.

**Pull request merged**
