### PR TITLE
Move fullscreen management from gfx to midp

### PR DESCRIPTION
**Pull request by TimAbraldes**
This applies over #1513 and #1514

### CODE REVIEW

**Comment by TimAbraldes** [comment]
Rebased onto just #1514

**Comment by mykmelez** [comment]
Is this just cleanup, or is there another benefit we should expect to get from it?

**Comment by TimAbraldes** [comment]
> Is this just cleanup, or is there another benefit we should expect to get from it?

This was preparatory for work I thought I was going to need to do to fix #1384. It seems like #1395 may actually have fixed #1384 so this is mostly cleanup now.

This change has some minor benefits like the fact that it moves our handling of switching to/from fullscreen from `com/sun/midp/lcdui/DisplayDevice.gainedForeground0.(II)V` to `com/sun/midp/main/MIDletProxyList.setForegroundInNativeState.(II)V` - which will probably make the switch happen in a slightly more timely fashion - and the fact that our fullscreen state will correctly reflect a "reset" of the foreground display since we now update fullscreen state in `com/sun/midp/main/MIDletProxyList.resetForegroundInNativeState.()V` - before we only handled `com/sun/midp/lcdui/DisplayDevice.gainedForeground0.(II)V` which probably doesn't get called during a reset.

I'm not aware of any user-visible effects of this patch, but if they exist they're likely to be in MIDlets that are not fullscreen.

**Comment by mykmelez** [comment]
Got it, thanks @TimAbraldes!

**Pull request merged**
