### PR TITLE
Remove getField calls

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
Depends on #1281.

**Comment by mykmelez** [comment]
The code changes are reasonable. What's the perf win?

**Comment by marco-c** [comment]
As https://github.com/mozilla/j2me.js/pull/1281#issuecomment-84064050.

**Comment by mykmelez** [comment]
Hmm, I don't actually see any perf improvements on this branch.

|      Test     | Baseline Mean |   Mean   |  +/- |   %   |       P       |    Min   |    Max   | 
|:--------------|--------------:|---------:|-----:|------:|--------------:|---------:|---------:|
| startupTime   |       1,295ms |  1,289ms | -6ms | -0.47 | INSIGNIFICANT |  1,243ms |  1,424ms | 
| totalSize     |      34,659kb | 34,721kb | 62kb |  0.18 | INSIGNIFICANT | 32,561kb | 35,844kb | 
| domSize       |         211kb |    211kb |  0kb | -0.01 | INSIGNIFICANT |    211kb |    211kb | 
| styleSize     |         433kb |    433kb |  0kb |  0.00 | INSIGNIFICANT |    432kb |    433kb | 
| jsObjectsSize |      17,618kb | 17,625kb |  7kb |  0.04 |         WORSE | 17,624kb | 17,628kb | 
| jsStringsSize |         668kb |    685kb | 16kb |  2.44 |         WORSE |    684kb |    686kb | 
| jsOtherSize   |      15,297kb | 15,337kb | 40kb |  0.26 | INSIGNIFICANT | 13,176kb | 16,461kb | 
| otherSize     |         432kb |    430kb | -2kb | -0.47 | INSIGNIFICANT |    430kb |    430kb | 

Runtime perf also seems equivalent for "basic test" runs (not a great metric, but it does seem reasonably stable across changes that don't add/remove basic tests).

Which makes this the kind of change we should start waving off at this stage in the development cycle. Nevertheless, I know that *getField* is slow, and this is low-risk given that bindings are a well-trod path, so let's take it.

**Pull request merged**
