### PR TITLE
Increase threshold for `getMediaTime`

### PR DESCRIPTION
**Pull request by TimAbraldes**
This fixes test failures that I'm seeing locally on master.

### CODE REVIEW

**Comment by mykmelez** [comment]
@TimAbraldes This is worth it if needed to pass the test on your system, although we're really stretching the utility of the test when we tolerate a 175ms delta on a 500ms timer. Any idea why the values of *mediaTime* and *actualTimeSlept* are so different for you?

**Comment by TimAbraldes** [comment]
Hmm. I really don't know! The values I was seeing for `actualTimeSlept` were about 505ms every time, and the values I saw for `mediaTime` were between 340ms and 365ms. Could there be something hardware-specific about my setup that causes these values to be so different from what others are seeing?

**Comment by mykmelez** [comment]
> Hmm. I really don't know! The values I was seeing for actualTimeSlept were about 505ms every time, and the values I saw for mediaTime were between 340ms and 365ms. Could there be something hardware-specific about my setup that causes these values to be so different from what others are seeing?

Hmm, unsure. There could be, and cc: @yxl and @marco-c for their thoughts. But I'll take this anyway in the meantime, as I don't want unreliable tests to block development or make it less efficient.

**Comment by yxl** [comment]
We changed the implementation of the audio player from using the Web Audio API to HTMLMediaElement. The media time got form HTMLMediaElement is not so accurate as that from the Web Audio API, especially for the short audio file.

**Pull request merged**
