### PR TITLE
Pre-initialize some other frequently used classes

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by TimAbraldes** [comment]
Is there something particularly useful to test here, or is the fact that it built good enough correctness-wise? What benefits should I be looking for perf-wise?

**Comment by marco-c** [comment]
This should reduce the number of class initialized checks that we need to do (and emit). So it should improve a bit both perf and memory usage (since we don't have to emit the checks, the code of the generated methods will also be smaller).

We're currently avoiding a lot of initialization checks because of a bug in the baseline JIT, so this won't change much at the moment, but it should improve perf once we've fixed the bug (https://github.com/mozilla/j2me.js/issues/1321).

**Comment by mykmelez** [comment]
Per a conversation in IRC, let's wait for startup perf tests that confirm this doesn't cause a regression.

**Comment by marco-c** [comment]
|      Test     | Baseline Mean |   Mean   |   +/-  |   %   |       P       |    Min   |    Max   | 
|:--------------|--------------:|---------:|-------:|------:|--------------:|---------:|---------:|
| startupTime   |       1,157ms |  1,210ms |   53ms |  4.62 | INSIGNIFICANT |  1,016ms |  5,934ms | 
| totalSize     |      27,567kb | 27,523kb |  -44kb | -0.16 | INSIGNIFICANT | 25,928kb | 28,755kb | 
| domSize       |         173kb |    173kb |    0kb |  0.08 |         WORSE |    173kb |    173kb | 
| styleSize     |         558kb |    536kb |  -22kb | -3.99 |        BETTER |    531kb |    536kb | 
| jsObjectsSize |      16,925kb | 17,010kb |   85kb |  0.50 |         WORSE | 16,694kb | 17,430kb | 
| jsStringsSize |         786kb |    779kb |   -8kb | -0.96 |        BETTER |    676kb |    822kb | 
| jsOtherSize   |       8,665kb |  8,554kb | -111kb | -1.29 | INSIGNIFICANT |  7,184kb |  9,379kb | 
| otherSize     |         460kb |    472kb |   12kb |  2.64 |         WORSE |    466kb |    488kb | 

|      Test     | Baseline Mean |   Mean   |  +/-  |   %   |       P       |    Min   |    Max   | 
|:--------------|--------------:|---------:|------:|------:|--------------:|---------:|---------:|
| startupTime   |       1,157ms |  1,103ms | -54ms | -4.67 |        BETTER |    952ms |  1,257ms | 
| totalSize     |      27,567kb | 27,610kb |  43kb |  0.16 | INSIGNIFICANT | 26,075kb | 28,699kb | 
| domSize       |         173kb |    173kb |   0kb |  0.07 |         WORSE |    173kb |    173kb | 
| styleSize     |         558kb |    536kb | -22kb | -3.99 |        BETTER |    536kb |    536kb | 
| jsObjectsSize |      16,925kb | 17,058kb | 133kb |  0.79 |         WORSE | 16,858kb | 17,421kb | 
| jsStringsSize |         786kb |    769kb | -17kb | -2.12 |        BETTER |    676kb |    781kb | 
| jsOtherSize   |       8,665kb |  8,601kb | -64kb | -0.74 | INSIGNIFICANT |  7,156kb |  9,625kb | 
| otherSize     |         460kb |    472kb |  13kb |  2.73 |         WORSE |    471kb |    488kb |

**Pull request merged**
