### PR TITLE
Add some tests

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by mykmelez** [comment]
Over in #1037, @brendandahl investigated disabling array bounds checks, but it didn't seem to have any perf impact. I wonder if it would have any impact to do that for strings. If so, and it was worth the correctness hit, then we'd have to break these tests. But we should take them in the meantime.

**Comment by mykmelez** [comment]
Most of these tests are licensed GPLv2, but tests/test/org/jikesrvm/basic/core/bytecode/TestInstanceOf.java and tests/test/org/jikesrvm/basic/core/bytecode/TestInvoke.java are licensed with the Eclipse Public License.

That's probably fine, since we already have other EPL files in our tests/ subdirectory, which @gerv has previously reviewed. So I'll merge this branch.

But note [this FAQ](http://www.eclipse.org/legal/eplfaq.php#GPLCOMPATIBLE), which says the EPL and GPL are incompatible.

@gerv Can you confirm that it's ok for us to have EPL-licensed tests (which don't get packaged and distributed) in our tests/ subdirectory?

**Comment by gerv** [comment]
Whether this is a problem or not depends on how the EPL and GPL bits of code relate to one another. If there's a pile of N tests, and you can run any subset of them, so they are independent, and some are EPL, and some are GPL, that seems fine to me. If the test harness is GPLed, that might be a problem. But wouldn't whoever wrote those tests and EPLed them have created that problem for themselves? Or were those tests, in their original context, run with a different harness?

Gerv

**Comment by marco-c** [comment]
The EPL licensed tests have been modified to run with our test harness, that is licensed under the GPL.

**Comment by gerv** [comment]
Hmm. I think that might be a problem, then. 
https://www.gnu.org/licenses/gpl-faq.html#IfInterpreterIsGPL suggests that if the input is "merely data", then you are OK, but a test program is not merely data; it calls and interacts with the facilities of the harness. So if your test harness is GPLed, I think non-GPL-compatible tests are a problem. Sorry :-( That covers both these and any others we may have.

Where did you get them? Can we ask for alternative terms?

**Comment by marco-c** [comment]
I took the tests from Jikes RVM (http://jikesrvm.org/). They're in the directory tests/test/org/jikesrvm/, so we could easily remove them if the developers don't allow us to use them with our test harness.

**Comment by gerv** [comment]
If you can provide me with a list of the files concerned (with their paths in the Jikes repo) I can talk to the developers and ask them to help us out here.

Do we have any tests we wrote that might be useful to them that we could offer in return? :-)

Gerv

**Comment by mykmelez** [comment]
> If you can provide me with a list of the files concerned (with their paths in the Jikes repo) I can talk to the developers and ask them to help us out here.

@gerv The files are:

From http://hg.code.sourceforge.net/p/jikesrvm/code/file/be916d5ac1fa/testing/tests/basic/src/test/org/jikesrvm/basic/bugs:
* tests/test/org/jikesrvm/basic/bugs/R1644449.java
* tests/test/org/jikesrvm/basic/bugs/R1644460.java
* tests/test/org/jikesrvm/basic/bugs/R1644460_B.java
* tests/test/org/jikesrvm/basic/bugs/R1657236.java

From http://hg.code.sourceforge.net/p/jikesrvm/code/file/be916d5ac1fa/testing/tests/basic/src/test/org/jikesrvm/basic/core/bytecode:
* tests/gnu/testlet/vm/TestArithmetic.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestArrayAccess.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestCompare.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestConstants.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestFieldAccess.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestFinally.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestFloatingRem.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestInstanceOf.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestInvoke.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestResolveOnCheckcast.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestResolveOnInstanceof.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestResolveOnInvokeInterface.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestReturn.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestSwitch.java
* tests/test/org/jikesrvm/basic/core/bytecode/TestThrownException.java

From http://hg.code.sourceforge.net/p/jikesrvm/code/file/be916d5ac1fa/testing/tests/basic/src/test/org/jikesrvm/basic/core/classloading:
* tests/test/org/jikesrvm/basic/core/classloading/TestClassLoading.java
* tests/test/org/jikesrvm/basic/core/classloading/TestUTF8.java

From http://hg.code.sourceforge.net/p/jikesrvm/code/file/be916d5ac1fa/testing/tests/basic/src/test/org/jikesrvm/basic/java/lang:
* tests/test/org/jikesrvm/basic/java/lang/TestMath.java

> Do we have any tests we wrote that might be useful to them that we could offer in return? :-)

Hmm, unsure. We've written a bunch of tests, and here are the ones I think we've written (based on their lack of a copyright header indicating a different origin):

* tests/gnu/testlet/vm/ArrayTest.java
* tests/gnu/testlet/vm/BytecodesTest.java
* tests/gnu/testlet/vm/ClassForNameInStaticInitializerTest.java
* tests/gnu/testlet/vm/ClassTest2.java
* tests/gnu/testlet/vm/ConditionsTest.java
* tests/gnu/testlet/vm/DupTest.java
* tests/gnu/testlet/vm/ExceptionTest.java
* tests/gnu/testlet/vm/FieldNotFoundException.java
* tests/gnu/testlet/vm/GetBytesTest.java
* tests/gnu/testlet/vm/InterfaceTest.java
* tests/gnu/testlet/vm/IsolatedClass.java
* tests/gnu/testlet/vm/LongTest.java
* tests/gnu/testlet/vm/MethodNotFoundException.java
* tests/gnu/testlet/vm/NativeTest.java
* tests/gnu/testlet/vm/NestedExceptionTest.java
* tests/gnu/testlet/vm/ObjectsTest.java
* tests/gnu/testlet/vm/OpsTest.java
* tests/gnu/testlet/vm/OverrideTest.java
* tests/gnu/testlet/vm/RuntimeTest.java
* tests/gnu/testlet/vm/StringTest.java
* tests/gnu/testlet/vm/TestInterfaceAbstractConcrete.java
* tests/gnu/testlet/vm/TestIsolate.java
* tests/gnu/testlet/vm/ThrowableTest.java
* tests/gnu/testlet/io/ByteArrayInputStreamTest.java
* tests/gnu/testlet/io/ByteArrayOutputStreamTest.java
* tests/gnu/testlet/io/DataInputStreamTest.java
* tests/gnu/testlet/io/DataOutputStreamTest.java
* tests/gnu/testlet/io/PrintStreamTest.java
* tests/gnu/testlet/lang/Boolean/BooleanTest2.java
* tests/gnu/testlet/lang/Date/DateTest.java
* tests/gnu/testlet/lang/Integer/IntegerTest.java
* tests/gnu/testlet/lang/Thread/wait.java

But I don't know if any would be interesting to (or compatible with) Jikes.

**Comment by marco-c** [comment]
There are also some tests in tests/java/lang/:
- tests/java/lang/TestArrayPrameter.java
- tests/java/lang/TestExceptionLocation.java
- tests/java/lang/TestNestedFinally.java
- tests/java/lang/TestStaticInit.java
- tests/java/lang/TestStaticInitRaceCondition.java
- tests/java/lang/TestString.java
- tests/java/lang/TestStringIntern.java
- tests/java/lang/TestThread.java
- tests/java/lang/TestThreadJoin.java
- tests/java/lang/TestThreadPriority.java

And a test written using Jasmin (http://jasmin.sourceforge.net/, very useful to write low-level tests):
- tests/gnu/testlet/vm/TestTwoFieldsSameName.j

There are other tests we wrote, but they're specific to J2ME, so they probably don't need them.

They could also use the tests we've copied from Mauve, but we haven't written them ourselves.

**Comment by gerv** [comment]
It seems that Jikes doesn't aggregate copyright, so we need to ask the individual contributors. Reading the blame, the people who created those tests are:

Peter Donald
Dave Grove
Ian Rogers
Erik Brangs

I have email addresses for all four. Can people fact-check the following email text to make sure I'm not telling them rubbish?

<snip>
Hi,

My name is Gerv; I'm with Mozilla. I'm emailing you because Mozilla is in the middle of writing a J2ME implementation in JavaScript ("j2me.js"), in order to run Midlets on our web-based mobile phone OS, Firefox OS. 

The engineers working on j2me.js would like to test the correctness of their implementation using some of the tests that you had a hand in writing for the Jikes RVM project. (A full list of the ones they are currently using is below - there are 22 tests in the current list.) j2me.js is licensed under the GPL, due to its use of existing GPLed code. More relevantly, so is the test harness. However, the Jikes RVM license is the Eclipse Public License, which is incompatible with the GPL. It could perhaps be argued either way, but it is our feeling that running EPL-licensed tests on a GPL-licensed test harness is not allowed, and so requires the permission of the copyright holders. The easiest and least ambiguous way to give this is to allow use of the code under a simple, permissive GPL-compatible license, such as the MIT license. (This would have no effect on the use of the code by Jikes RVM.)

If you are willing to help us out in this way, please could you reply to this email with the following text?

"I grant permission for Mozilla to use the tests I have contributed to the JikesRVM project under the terms of the MIT license."

If you are not ready to take that step, I am very happy to answer any questions you may have about what we are trying to do. Many thanks for your time and help :-)

Gerv

-- XXX include list of tests here --

</snip>

Gerv

**Comment by mykmelez** [comment]
> I'm emailing you because Mozilla is in the middle of writing a J2ME implementation in JavaScript ("j2me.js"), in order to run Midlets on our web-based mobile phone OS, Firefox OS.

I would make this: I'm emailing you because Mozilla is in the middle of writing a Java virtual machine and J2ME implementation in JavaScript ("j2me.js"), in order to run Midlets on our web-based mobile phone OS, Firefox OS.

(Adding "Java virtual machine", since we're writing the VM as well as the J2ME implementation.)

Otherwise, it sounds great!

**Comment by gerv** [comment]
Email sent.

Gerv

**Comment by gerv** [comment]
One of the people I emailed asks:

- Do you have access to the JCK? If so, why aren't the tests sufficient?
- Do you have any plans to write a test suite that can be used by other VMs (e.g. something like Malva https://github.com/jatovm/malva)?

Gerv

**Comment by gerv** [comment]
Also, David Grove says that the original copyright of these tests may be owned by IBM, done as work for hire. He's going to ask about relicensing them. However, I suspect any relicensing will be limited to a strict list of tests. So if Jikes has any more tests we might like to use, now is the time to figure out which ones they are!

Gerv

**Comment by mykmelez** [comment]
> Do you have access to the JCK? If so, why aren't the tests sufficient?

I don't think so, as the JCK "is available to developers who are planning to deploy a compatible Java implementation based on code derived from OpenJDK, or are participating in OpenJDK research, bug fixes, code enhancement and/or ports to other hardware/software architectures," <http://openjdk.java.net/groups/conformance/JckAccess/>; and our implementation is not based on OpenJDK, nor are we participating in the listed OpenJDK activities.

That page also references an OpenJDK Community TCK License Agreement (OCTLA), which I haven't investigated. And Apache has had its troubles with the JCK <http://www.apache.org/jcp/sunopenletterfaq.html>, which might be relevant to our situation. So there could be other stumbling blocks.


> Do you have any plans to write a test suite that can be used by other VMs (e.g. something like Malva https://github.com/jatovm/malva)?

We don't have plans to do this, but I would certainly be happy to contribute tests to such a suite.

**Comment by marco-c** [comment]
> Do you have any plans to write a test suite that can be used by other VMs (e.g. something like Malva https://github.com/jatovm/malva)?

It's worth noting that our tests are more or less compatible with Mauve (https://sourceware.org/mauve/), that is an earlier attempt at a collaborative Java test suite.

**Pull request merged**
