### PR TITLE
Optimize drawString

### PR DESCRIPTION
**Pull request by nnethercote**
A warning: I was unable to run the tests -- some kind of Python exception -- so I haven't been able to test that strings containing emoji work correctly.

### CODE REVIEW

**Comment by marco-c** [comment]
@nnethercote could you merge from master? The Travis build is failing because it can't download the SpiderMonkey shell (fixed in #1318)

> I was unable to run the tests -- some kind of Python exception -- 

Could you file an issue with more details?

**Comment by nnethercote** [comment]
I rebased and have updated the pushed changesets.

I filed #1322 for the `make tests` failure.

**Comment by marco-c** [comment]
There's one test failure, you can run it manually by opening the following URL in your browser:
http://localhost:8000/index.html?fontSize=12&midletClassName=gfx/DrawStringWithCopyrightAndRegisteredSymbols&jars=tests/tests.jar&logConsole=web,page&logLevel=log

(The expected result is the image "DrawStringWithCopyrightAndRegisteredSymbols.png" in gfx/)

**Comment by nnethercote** [comment]
The DrawStringWithEmojiTest should have failed as well. Did it? I'm having trouble reading the Travis output... maybe it was skipped because DrawStringWithCopyrightAndRegisteredSymbols failed prior to it?

**Comment by mykmelez** [comment]
Lines 4648 - 4651 of the Travis output show that DrawStringWithEmojiTest passed with slightly fewer different pixels than the allowed number:

> | PASS - 1082 <= 1133 
> | DONE 
>[info] [phantom] Step anonymous 485/556 http://localhost:8000/main.html?fontSize=12&midletClassName=gfx/DrawStringWithEmojiTest&jars=tests/tests.jar&logConsole=web,page&logLevel=log (HTTP 200)
>PASS gfx/DrawStringWithEmojiTest - Pass

**Comment by mykmelez** [comment]
Lines 4995 - 4998 show the DrawStringWithCopyrightAndRegisteredSymbols failure:

> | FAIL - 267 <= 244 
> | DONE 
> [info] [phantom] Step anonymous 555/598 http://localhost:8000/main.html?fontSize=12&midletClassName=gfx/DrawStringWithCopyrightAndRegisteredSymbols&jars=tests/tests.jar&logConsole=web,page&logLevel=log (HTTP 200)
> FAIL gfx/DrawStringWithCopyrightAndRegisteredSymbols - Failure

**Comment by mykmelez** [comment]
Line 4994 is a data: URL representing a screenshot of the test that failed, which is blank/white, indicating that nothing was drawn. Here's the original/reference image, in which two characters are drawn:

drawstringwithcopyrightandregisteredsymbols

**Comment by marco-c** [comment]
Unfortunately in some cases the tests are not completely reliable, for example in this case (267 <= 244) a few pixels would have made the test pass anyway.

**Comment by marco-c** [comment]
@TimAbraldes can you review this, since you've been looking at gfx code lately?
I think some changes in this PR conflict with the changes you're making in #1277, so it'd be good to synchronize and choose the best option.

**Comment by TimAbraldes** [comment]
> @TimAbraldes can you review this, since you've been looking at gfx code lately?
I think some changes in this PR conflict with the changes you're making in #1277, so it'd be good to synchronize and choose the best option.

Sure, I can review this! I'm splitting #1277 into smaller patches so it probably makes sense to land these changes first. I can rebase the smaller patches as necessary.

**Comment by TimAbraldes** [comment]
This looks good to me.

I ran the `Graphics` benchmark I'm developing in #1315 on this branch and got these results:

Baseline (current master):

    Graphics.drawString baseline centered
      Avg ms to perform 500 ops: 27
      Avg ops per ms: 18
    Offscreen Graphics.drawString baseline centered
      Avg ms to perform 500 ops: 26
      Avg ops per ms: 19

Bench (this branch):

    Graphics.drawString baseline centered
      Avg ms to perform 500 ops: 26
      Avg ops per ms: 19
    Offscreen Graphics.drawString baseline centered
      Avg ms to perform 500 ops: 24
      Avg ops per ms: 20

A modest improvement. I should note that I'm not really certain how variable these numbers are.

**Pull request merged**
