### PR TITLE
WIP Always run FG MIDlet. Pause inactive FG threads

### PR DESCRIPTION
**Pull request by TimAbraldes**
Pause all non-BG MIDlets when app is not active, and activate them again
when the app becomes active. First, notify all
non-BG MIDlets that they will be paused/resumed by sending a
PAUSE_ALL_EVENT when the app is not active and an ACTIVATE_ALL_EVENT
when the app has become active again. When all non-BG MIDlets have
responded to being paused, freeze their threads in the JVM (this part
hasn't been implemented yet).

Launch the BG MIDlet when launching the app. This is less fragile than
guessing which MIDlet is the FG MIDlet and launching that when the BG
MIDlet launches.

### CODE REVIEW

**Comment by TimAbraldes** [comment]
This PR is investigative work that is intended to eventually complete #1543

**Comment by TimAbraldes** [comment]
Rebased to current master and made tests pass locally.

**Comment by TimAbraldes** [comment]
Updated commit message:

Target the FG MIDlet for launch. Detect when launching a FG MIDlet that
has a BG MIDlet and launch the BG MIDlet during startup of the MIDlet
suite. This is less fragile than guessing which MIDlet is the FG
MIDlet and launching that when the BG MIDlet launches. Additionally,
this practically eliminates our warm startup time.

Pause all non-BG MIDlets when app is not active, and activate them again
when the app becomes active. First, notify all
non-BG MIDlets that they will be paused/resumed by sending a
PAUSE_ALL_EVENT when the app is not active and an ACTIVATE_ALL_EVENT
when the app has become active again. When all non-BG MIDlets have
responded to being paused/resumed, freeze/unfreeze their threads in
the JVM.

TODO: Can we freeze the AMS isolate?
TODO: Some apps experience issues when exiting via Java calls
TODO: Some apps show less ideal alerts when FG MIDlet is running

**Comment by marco-c** [comment]
> TODO: Can we freeze the AMS isolate?

IIRC the AMS isolate is the isolate associated with the first MIDlet that is created, so if you start the FG MIDlet first and you want to freeze its threads, you need to freeze the AMS isolate.
(I haven't looked at the patch yet, so I don't know if you've somehow changed that)

**Comment by mykmelez** [comment]
I can reproduce the test failure locally on my Mac, so it isn't specific to Travis's Linux build environment.

**Comment by TimAbraldes** [comment]
The work in this patch is superseded by work that will be posted in upcoming PRs

**Pull request closed without merging**
