### PR TITLE
Run main class static initializer before calling main method.

### PR DESCRIPTION
**Pull request by brendandahl**

### CODE REVIEW

**Comment by TimAbraldes** [comment]
Is this a perf improvement? Do we have numbers showing its effect?

**Comment by brendandahl** [comment]
This is purely a correctness issue.

**Comment by brendandahl** [comment]
Let's hold off for a sec, I think I can write a test for this.

**Comment by brendandahl** [comment]
@TimAbraldes added the test

**Comment by TimAbraldes** [comment]
Great! Tests pass on Travis. Also verified that I could run my favorite MIDlet with this patch applied

**Pull request merged**
