### PR TITLE
Compiler Optimizations for Regex

### PR DESCRIPTION
**Pull request by mbebenita**
1. This PR increases the compilation threshold from 2000 to 3000 bytecodes (bytes, not instructions). This is now large enough to compile hot methods in the regexp library.

2. This PR also optimizes interface calls, which were slo, allocated memory and prevented inlining.

`Original: 82660ms`
`After 1: 6365ms, 12X faster.`
`After 2: 200ms, 440X faster.`

### CODE REVIEW

**Comment by mbebenita** [comment]
The bug was causing correctness issues and made the entire benchmark run a lot faster. Perf now is a more sensible, 3980ms or ~20x.

**Comment by marco-c** [comment]
Can you run the startup benchmark on a device?

**Comment by mykmelez** [comment]
> Can you run the startup benchmark on a device?
> I wonder how the 2000 -> 3000 increase affects memory usage.

@mbebenita Ping, have you had a chance to do this yet?

**Comment by mykmelez** [comment]
> @mbebenita Ping, have you had a chance to do this yet?

@mbebenita is on PTO, so I've run the startup benchmark, which shows no change:

|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:34.0) Gecko/34.0 Firefox/34.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|       Test      | Baseline Mean |    Mean    |    +/-   |     %    |     P    |     Min    |     Max    | 
|:----------------|--------------:|-----------:|---------:|---------:|---------:|-----------:|-----------:|
| startupTime     |      11,991ms |   11,662ms |   -328ms |    -2.74 |     SAME |   10,810ms |   14,218ms | 
| vmStartupTime   |       2,248ms |    2,211ms |    -37ms |    -1.64 |     SAME |    1,975ms |    2,358ms | 
| bgStartupTime   |       1,869ms |    1,835ms |    -35ms |    -1.86 |     SAME |    1,682ms |    2,510ms | 
| fgStartupTime   |       7,873ms |    7,616ms |   -257ms |    -3.26 |     SAME |    6,880ms |    9,420ms | 
| *totalSize*     |    *22,615kb* | *22,482kb* | *-132kb* |  *-0.59* |   *SAME* | *21,679kb* | *23,306kb* | 
| *domSize*       |        *71kb* |     *71kb* |    *0kb* |  *-0.07* |   *SAME* |     *71kb* |     *71kb* | 
| *styleSize*     |       *300kb* |    *298kb* |   *-2kb* |  *-0.74* |   *SAME* |    *291kb* |    *305kb* | 
| *jsObjectsSize* |    *15,556kb* | *15,501kb* |  *-55kb* |  *-0.36* | *BETTER* | *15,479kb* | *15,535kb* | 
| *jsStringsSize* |       *945kb* |    *653kb* | *-291kb* | *-30.84* | *BETTER* |    *653kb* |    *656kb* | 
| *jsOtherSize*   |     *5,518kb* |  *5,748kb* |  *230kb* |   *4.17* |  *WORSE* |  *4,876kb* |  *6,518kb* | 
| *otherSize*     |       *225kb* |    *211kb* |  *-13kb* |  *-5.94* |   *SAME* |    *166kb* |    *271kb* | 
| *USS*           |    *49,637kb* | *50,113kb* |  *476kb* |   *0.96* |  *WORSE* | *48,420kb* | *51,704kb* | 
| *peakRSS*       |         *0kb* |    *NaNkb* |  *NaNkb* |    *NaN* |   *SAME* |    *NaNkb* |    *NaNkb* | 

I do, however, see an improvement when using a midlet that relies on this regex library. And I see an improvement on the regex benchmark, whose init/match times drop from about 60/90 to about 20/40 when the benchmark is re-run after compilation is completed (and cached).

Since the regex library and benchmark (and the interface optimization change) have already landed, the only change here is the one-line bump in threshold for compiling methods, which I've tested locally. So I'll go ahead and merge this branch via my local clone.

**Comment by marco-c** [comment]
We should probably investigate memory usage better with the different threshold (https://github.com/mozilla/j2me.js/issues/1481). Unfortunately the memory results of the startup benchmark aren't always reliable.

**Pull request merged**
