### PR TITLE
Add USS and peakRSS values to the startup benchmark

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
The results aren't really stable (for example I've run the benchmark on master with no changes and it showed an improvement, but this is true for the other memory values as well)

**Comment by mykmelez** [comment]
Can we de-emphasize the numbers that we don't yet trust? I'm thinking something like making their text be grey, or in italic; anything to reduce their visibility relative to the numbers that we have more confidence in.

**Comment by marco-c** [comment]
I've made the text italic for memory values:

|      Config      |                                 Value                                | 
|:-----------------|:---------------------------------------------------------------------|
| User Agent       | Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0 | 
| Rounds           | 1                                                                    | 
| Delay(ms)        | 2000                                                                 | 
| Delete FS        | no                                                                   | 
| Delete JIT CACHE | no                                                                   | 

|       Test      | Baseline Mean |     Mean    |  +/-  |   %   |   P   |     Min     |     Max     | 
|:----------------|--------------:|------------:|------:|------:|------:|------------:|------------:|
| startupTime     |           n/a |     1,059ms |   n/a |   n/a |   n/a |     1,059ms |     1,059ms | 
| vmStartupTime   |           n/a |       224ms |   n/a |   n/a |   n/a |       224ms |       224ms | 
| bgStartupTime   |           n/a |       215ms |   n/a |   n/a |   n/a |       215ms |       215ms | 
| fgStartupTime   |           n/a |       620ms |   n/a |   n/a |   n/a |       620ms |       620ms | 
| *totalSize*     |         *n/a* |  *28,040kb* | *n/a* | *n/a* | *n/a* |  *28,040kb* |  *28,040kb* | 
| *domSize*       |         *n/a* |     *171kb* | *n/a* | *n/a* | *n/a* |     *171kb* |     *171kb* | 
| *styleSize*     |         *n/a* |     *536kb* | *n/a* | *n/a* | *n/a* |     *536kb* |     *536kb* | 
| *jsObjectsSize* |         *n/a* |  *17,217kb* | *n/a* | *n/a* | *n/a* |  *17,217kb* |  *17,217kb* | 
| *jsStringsSize* |         *n/a* |     *725kb* | *n/a* | *n/a* | *n/a* |     *725kb* |     *725kb* | 
| *jsOtherSize*   |         *n/a* |   *8,917kb* | *n/a* | *n/a* | *n/a* |   *8,917kb* |   *8,917kb* | 
| *otherSize*     |         *n/a* |     *473kb* | *n/a* | *n/a* | *n/a* |     *473kb* |     *473kb* | 
| *USS*           |         *n/a* | *188,668kb* | *n/a* | *n/a* | *n/a* | *188,668kb* | *188,668kb* | 
| *peakRSS*       |         *n/a* | *326,692kb* | *n/a* | *n/a* | *n/a* | *326,692kb* | *326,692kb* |

**Comment by mykmelez** [comment]
This seems to have broken benchmarking on Nightly, where I get the error `[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIMemoryReporterManager.residentUnique]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: http://localhost/~myk/j2me.js/bld/main-all.js :: sampleMemory/< :: line 820"  data: no] `.

**Pull request merged**
