### PR TITLE
Implement refresh0.

### PR DESCRIPTION
**Pull request by brendandahl**
Depends on #1519

### CODE REVIEW

**Comment by marco-c** [comment]
How does perf in general look like after #1519?

**Comment by mykmelez** [comment]
> How does perf in general look like after #1519?

In my most recent tests, the UI is more responsive, but it's also more flickery.

**Comment by mykmelez** [comment]
#1519 has landed, and this now has conflicts with master. @brendandahl can you merge from master and resolve those conflicts?

**Comment by brendandahl** [comment]
> How does perf in general look like after #1519?

Ask for a link to some notes.

**Comment by mykmelez** [comment]
> Ask for a link to some notes.

Erm, can you elaborate?

**Comment by mykmelez** [comment]
This resolves the flicker regression that was introduced by #1519. The perf impact isn't entirely clear, but GraphicsBench outputs similar numbers before and after this change, and tests of a complex midlet on a device suggest that the UI appears to be just as responsive, if not more so, afterward.

**Pull request merged**
