### PR TITLE
Don't wait for localmsg before starting FG MIDlet

### PR DESCRIPTION
**Pull request by marco-c**

### CODE REVIEW

**Comment by marco-c** [comment]
This saves ~200 ms on desktop on the time to start the FG MIDlet. Unfortunately the time to *gainedForeground0* doesn't seem changed much (maybe ~40 ms, but it's hard to tell).

Before:
```
time loadApp 357.14268300000003 
time initFS 447.402411 
time start 447.855338 
time jvm.startIsolate0 476.528302 
time start FG MIDlet: 883.24169
time DisplayDevice.gainedForeground0 2088.421883

time loadApp 312.614123 
time initFS 398.349918 
time start 398.816701 
time jvm.startIsolate0 427.395578 
time start FG MIDlet: 874.316509 
time DisplayDevice.gainedForeground0 2070.988255
```

After:
```
time loadApp 312.29235 
time initFS 401.40902 
time start 401.863872 
time jvm.startIsolate0 430.34008 
time start FG MIDlet: 666.6525439999999 
time DisplayDevice.gainedForeground0 2046.128708

time loadApp 314.251226 
time initFS 402.34172 
time start 402.84223099999997 
time jvm.startIsolate0 431.397013 
time start FG MIDlet: 682.021333 
time DisplayDevice.gainedForeground0 2028.124687
```

**Comment by marco-c** [comment]
On a Flame:

Before:
```
time loadApp 1860.88328
time restore compiled method cache 1929.425884
time initFS 2116.690259
time start 2305.531196
time jvm.startIsolate0 2552.544582
time start FG MIDlet: 6939.835986
time DisplayDevice.gainedForeground0 16685.947128

time loadApp 1889.618802
time restore compiled method cache 1970.716769
time initFS 2140.409687
time start 2310.602707
time jvm.startIsolate0 2578.124687
time start FG MIDlet: 6581.527081
time DisplayDevice.gainedForeground0 16215.394420999999
```

After:
```
time loadApp 2000.0280199999997
time restore compiled method cache 2064.63776
time initFS 2259.354062
time start 2388.843801
time jvm.startIsolate0 2701.044531
"time start FG MIDlet: 5191.929895
time DisplayDevice.gainedForeground0 17527.733639000002

time loadApp 1933.875416
time restore compiled method cache 1996.3914570000002
time initFS 2172.9690100000003
time start 2320.722708
time jvm.startIsolate0 2595.364009
time start FG MIDlet: 5076.601509
time DisplayDevice.gainedForeground0 17947.9214
```

**Comment by marco-c** [comment]
I've tested this with the startup benchmark, it was ~450 ms faster.
Memory usage was 6 MB less than master, but I don't see how it would be possible.

**Comment by mykmelez** [comment]
> Memory usage was 6 MB less than master, but I don't see how it would be possible.

Hmm, I don't see how either, but perhaps this was just an artifact of the test you used at the time.

On desktop (30 rounds, 1.5s delay), with a complex midlet, I don't see any significant difference in the startup benchmark:

|      Test     | Baseline Mean |   Mean   |   +/-  |   %   |       P       |    Min   |    Max   | 
|:--------------|--------------:|---------:|-------:|------:|--------------:|---------:|---------:|
| startupTime   |       1,134ms |  1,124ms |   -9ms | -0.83 | INSIGNIFICANT |  1,090ms |  1,229ms | 
| totalSize     |      26,301kb | 26,109kb | -192kb | -0.73 | INSIGNIFICANT | 25,081kb | 26,812kb | 
| domSize       |         152kb |    152kb |    0kb |  0.00 | INSIGNIFICANT |    152kb |    152kb | 
| styleSize     |         412kb |    412kb |    0kb | -0.02 |        BETTER |    411kb |    412kb | 
| jsObjectsSize |      16,789kb | 16,781kb |   -8kb | -0.05 |        BETTER | 16,772kb | 16,790kb | 
| jsStringsSize |         624kb |    621kb |   -3kb | -0.48 |        BETTER |    621kb |    623kb | 
| jsOtherSize   |       7,930kb |  7,749kb | -181kb | -2.28 | INSIGNIFICANT |  6,730kb |  8,441kb | 
| otherSize     |         395kb |    395kb |    0kb |  0.01 | INSIGNIFICANT |    394kb |    396kb | 

On a Flame with FxOS 2.1 (30 rounds, 5s delay), I see the same:

|      Test     | Baseline Mean |   Mean   |  +/-  |   %   |       P       |    Min   |    Max   | 
|:--------------|--------------:|---------:|------:|------:|--------------:|---------:|---------:|
| startupTime   |      11,315ms | 11,653ms | 338ms |  2.99 | INSIGNIFICANT | 10,686ms | 12,470ms | 
| totalSize     |      22,226kb | 22,230kb |   3kb |  0.01 | INSIGNIFICANT | 21,337kb | 22,990kb | 
| domSize       |          71kb |     71kb |   0kb | -0.10 | INSIGNIFICANT |     70kb |     71kb | 
| styleSize     |         294kb |    291kb |  -3kb | -0.92 | INSIGNIFICANT |    284kb |    300kb | 
| jsObjectsSize |      15,399kb | 15,387kb | -12kb | -0.08 |        BETTER | 15,370kb | 15,403kb | 
| jsStringsSize |         636kb |    632kb |  -3kb | -0.51 |        BETTER |    632kb |    633kb | 
| jsOtherSize   |       5,596kb |  5,629kb |  33kb |  0.60 | INSIGNIFICANT |  4,798kb |  6,441kb | 
| otherSize     |         232kb |    220kb | -12kb | -5.15 | INSIGNIFICANT |    167kb |    287kb |

**Comment by marco-c** [comment]
> Hmm, I don't see how either, but perhaps this was just an artifact of the test you used at the time.

Actually, the test I've run is the startup benchmark (and I did run it 3 days ago :smiley:) on a Flame with Firefox OS 2.0.
I wasn't able to copy and paste the results table because WebIDE crashed when I selected the text.

I think we should take the change, even if it isn't clear whether it improves startup pref or leaves it unaffected, because there's no reason why we should wait for the localmsg server to be running before starting foreground MIDlets.

**Comment by mykmelez** [comment]
> I think we should take the change, even if it isn't clear whether it improves startup pref or leaves it unaffected, because there's no reason why we should wait for the localmsg server to be running before starting foreground MIDlets.

Yes, I agree.

**Comment by mykmelez** [comment]
This seems to have caused a firstrun regression: an app never gets past the "loading midlet" stage on firstrun (second run is fine). So I'm going to revert this, and then @marco-c will figure out the regression and resubmit the PR.

**Pull request merged**
