### PR TITLE
WIP: Remove support for overrides

### PR DESCRIPTION
**Pull request by marco-c**
Depends on #1301 and #1314.

### CODE REVIEW

**Comment by marco-c** [comment]
Need to wait for the other two PRs to land and then fix the test result (I suspect it isn't due to this PR, but to the combined effect of the other two PRs)

**Comment by brendandahl** [comment]
We may not want to wait for the self hosted strings patch to do this. I played a bit with it to see if I could get performance back to what it was, but there was nothing immediately noticeable that was wrong.

**Comment by marco-c** [comment]
The problem is that we can't completely remove support for overrides unless we remove the String overrides.

**Comment by brendandahl** [comment]
Can't we just convert it to custom and make all the overrides native?

**Comment by marco-c** [comment]
Ah yes, sure. I'll do that.

**Comment by marco-c** [comment]
Obsoleted by https://github.com/mozilla/j2me.js/pull/1391.

**Pull request closed without merging**
