### PR TITLE
Load emoji earlier

### PR DESCRIPTION
**Pull request by marco-c**
Depends on #1512.

### CODE REVIEW

**Comment by marco-c** [comment]
On desktop, it took ~160 ms to load the images (com/sun/midp/lcdui/DisplayDevice.gainedForeground0.(II)V: count: 1, self: 162.582 ms, total: 162.582 ms).

**Comment by mykmelez** [comment]
What else does this need to be ready now that #1512 has landed?

**Comment by mykmelez** [comment]
@marco-c Can you merge master into this branch, so GitHub's "Files changed" view shows only the changes that haven't been merged yet?

**Comment by marco-c** [comment]
> @marco-c Can you merge master into this branch, so GitHub's "Files changed" view shows only the changes that haven't been merged yet?

Now that I've done this, I've realized this doesn't actually depend on #1512.

**Comment by mykmelez** [comment]
|      Config      |                         Value                         | 
|:-----------------|:------------------------------------------------------|
| User Agent       | Mozilla/5.0 (Mobile; rv:40.0) Gecko/40.0 Firefox/40.0 | 
| Rounds           | 30                                                    | 
| Delay(ms)        | 5000                                                  | 
| Delete FS        | no                                                    | 
| Delete JIT CACHE | no                                                    | 

|       Test      | Baseline Mean |     Mean    |     +/-     |    %    |     P    |     Min     |     Max     | 
|:----------------|--------------:|------------:|------------:|--------:|---------:|------------:|------------:|
| startupTime     |      14,159ms |    14,227ms |        68ms |    0.48 |     SAME |    13,145ms |    15,541ms | 
| vmStartupTime   |       3,015ms |     3,163ms |       148ms |    4.91 |    WORSE |     2,829ms |     3,483ms | 
| bgStartupTime   |       1,019ms |     1,006ms |       -13ms |   -1.27 |     SAME |       942ms |     1,108ms | 
| fgStartupTime   |      10,125ms |    10,058ms |       -67ms |   -0.66 |     SAME |     8,997ms |    11,280ms | 
| *totalSize*     |    *22,179kb* |  *22,165kb* |     *-13kb* | *-0.06* |   *SAME* |  *20,527kb* |  *23,516kb* | 
| *domSize*       |        *73kb* |      *73kb* |       *0kb* | *-0.23* |   *SAME* |      *73kb* |      *74kb* | 
| *styleSize*     |       *282kb* |     *280kb* |      *-2kb* | *-0.71* |   *SAME* |     *272kb* |     *288kb* | 
| *jsObjectsSize* |    *15,581kb* |  *15,563kb* |     *-18kb* | *-0.11* |   *SAME* |  *14,900kb* |  *15,952kb* | 
| *jsStringsSize* |       *919kb* |     *909kb* |     *-10kb* | *-1.11* | *BETTER* |     *873kb* |     *949kb* | 
| *jsOtherSize*   |     *5,043kb* |   *5,082kb* |      *39kb* |  *0.77* |   *SAME* |   *3,973kb* |   *6,072kb* | 
| *otherSize*     |       *280kb* |     *258kb* |     *-22kb* | *-7.74* |   *SAME* |     *205kb* |     *323kb* | 
| *USS*           |    *60,473kb* |  *55,355kb* |  *-5,117kb* | *-8.46* | *BETTER* |  *52,920kb* |  *58,244kb* | 
| *peakRSS*       |   *162,132kb* | *148,436kb* | *-13,696kb* | *-8.45* |   *SAME* | *148,436kb* | *148,436kb* |

**Comment by marco-c** [comment]
So it's probably a warm-startup win only (although I expect it could improve startup time in general in the future, if we somehow improve the order things gets loaded at startup).

**Pull request merged**
